
site_name: SparkFun GNSS Combo Breakout - ZED-F9P, NEO-D9S (Qwiic) Product Manual
site_description: A hookup guide for the SparkFun GNSS Combo Breakout - ZED-F9P, NEO-D9S (Qwiic) (SPX-20167)
site_url: https://github.com/sparkfun/SparkFun_GNSS_Combo_Breakout-ZED-F9P_NEO-D9S

edit_uri: edit/main/docs/

copyright:
  Copyright 2023 - <a href="https://www.sparkfun.com/" target="_blank" rel="noopener">SparkFun Electronics&#174;<br>
  <a href="https://goo.gl/maps/vkstCpQZW6jZMjzYA" target="_blank" rel="noopener">6333 Dry Creek Parkway, Niwot, Colorado 80503</a>

# Configuration for webpage theme
theme:
  # Theme: https://squidfunk.github.io/mkdocs-material/
  name: material

  # Header Logo
  logo: assets/sfe_logo_sm.png

  # Icon in Browser Tab (must be square img - i.e. 32x32 pixels)
  favicon: assets/sfe_logo_sq.png

  # Page Font
  font:
    text: Roboto
    code: Roboto Mono
  
  # Features to Include (ref. theme docsumentation)
  features:

    # Enable copy button on code blocks
    - content.code.copy

    # Enable annotations in code blocks
    - content.code.annotate

    # Enable "view source" and "edit this page" buttons
    - content.action.edit
    # - content.action.view

    # Enable Navigation buttons in footer (i.e. previous/next)
    - navigation.footer

    # Enables anchor tracking (updates page url with the section user is on)
    # i.e. https://docs.sparkfun.com/<page link>/#<sub-section>
    - navigation.tracking

    # Enables tabs for navigating website
    - navigation.tabs
    # Keeps tabs visible in header when scrolling
    - navigation.tabs.sticky
    
    # Adds pop-up button just below header (when user starts to scroll up)
    # Allows users to easily jump to the beginning of the page
    - navigation.top

    # Renders path for page navigation at top of the page (makes page navigation more mobile friendly)
    - navigation.path

  # Adds light/dark theme to webpage
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      accent: red
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: red
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference    

  # Configures icons of callout boxes
  icon:
    # Sets repo icon to GitHub icon
    repo: fontawesome/brands/github
    
    # Sets icons for "view source" (commented out) and "edit this page" buttons
    edit: material/file-document-edit-outline
    # view: material/file-code-outline

    # Admonition Icons
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: simple/sparkfun
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      # Add custom admonitions
      github: simple/github
      arduino: simple/arduino
      python: simple/python
      code: fontawesome/regular/file-code
      terminal: octicons/terminal-16
      serial: fontawesome/solid/display

  # Adds PDF icon to download hookup guide
  custom_dir: docs/overrides


# Included MkDocs plugins
# Add the installation of any new plugins to the ./github/workflows/mkdocs.yml file also
plugins:
  - search
  # Add revision date
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  # Add git commiters at bottom of the page
  - git-committers:
      repository: sparkfun/SparkFun_GNSS_Combo_Breakout-ZED-F9P_NEO-D9S
      branch: docs-test
  # Add git authors at bottom of the page
  - git-authors
  # Enables use of Git submodules and larger code base
  - monorepo

# Included Markdown extensions
markdown_extensions:
  - toc:
      permalink: '🔗'
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # base_path: ['./docs']
      url_download: true
      url_max_size: 0
      url_timeout: 0
      url_request_headers: {}
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - tables
  - admonition
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true


# Configures social icons in footer
extra:
  social:
    - icon: sfe_logo # simple/sparkfun
      link: https://www.sparkfun.com/products/20168
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/sparkfun
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sparkfun
    - icon: fontawesome/brands/github
      link: https://www.github.com/sparkfun
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SparkFun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sparkfun


# Configures styling for PDF rendering and webpage layout
extra_css:
  - overrides/extra.css


nav:
  - Hookup Guide:
    - Introduction: index.md
    - Hardware Overview: hardware_overview.md
    - Hardware Assembly: hardware_assembly.md
    - SparkFun GNSS Combo Breakout ZED-F9P/NEO-D9S Arduino Library:
      - Software Setup: software_overview.md
      - Arduino Examples: examples.md
  - Resources: resources.md
  - Support:
    - Troubleshooting: troubleshooting.md
    - Submit Issues: file_issue.md
    - Contribute: contribute.md
    
    
    